### ISSUE TITLE
NullReferenceException in method ExplicitVisit in SQLHandler.cs When Creating Views For Entities Using CDMUtil_ConsoleApp

### ISSUE THREAD

**Issue by TravisKale** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#130]
I am using CDMUtil_ConsoleApp to create views on a Synapse Serverless SQL endpoint.  I am able to create views for my tables successfully, but when trying to create views for entities, I receive a NullReferenceException within the below method signature.  It appears the SchemaIdentifier object is null.   I have tried two different entities, both with the same result, both default entities.   I have ensured all tables, written to the console prior to the error occurring, exist & have views created for them.  Any tips on what to look for?

```
        public override void ExplicitVisit(CreateViewStatement node)
        {
            if (node.SchemaObjectName != null )
            {
                
                node.SchemaObjectName.SchemaIdentifier.Value = sparkSQL ? dbName : schema;
            }
            base.ExplicitVisit(node);
        }
```

**Comment by jiyada** [comment]
Can you please share your config (after removing the sensitive information) - want to make sure what configuration option you are using.

Here are the two typical option to generate entity's view on Synapse. 

Option 1 : Using enhanced metadata 
[Enhanced metadata feature](https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/azure-data-lake-enhanced-metadata#enhanced-metadata-preview) is enabled while installing the Export to data lake add-in from LCS. Follow the steps bellow to validate if enhanced metadata feature is on 1. From Finance and Operation > Export to data lake form – use option Choose table using entities and add a entity to service.
2. In the storage account validate that Entities.manifest.cdm.json file is generated and corresponding entity metadata is generated.
[yourstorageaccount/dynamics365-financeandoperations/yourenvironment/Entities/Entities.manifest.cdm.json](https://ftfinanced365fo.blob.core.windows.net/dynamics365-financeandoperations/finance.sandbox.operations.dynamics.com/Entities/Entities.manifest.cdm.json)
3. Update the CDMUtil ManifestURL to URL of Entities.manifest.cdm.json
4. Run the CDMUtil console App 

Option 2 : Using ProcessEntities with EntityList.json 
1.	Update entity list in the file  EntityList.json under CDMUtil folder 
2.	Update config AXDBConnectionString to local AXDB development or sandbox environment 
3.	Update config ProcessEntities = true

**Comment by TravisKale** [comment]
@jiyada.  

When I try option 1 I get the error message:  "Invalid object name 'INVENTWAREHOUSEONHANDAGGREGATEDVIEW'"   In the instructions  troubleshooting section it says to proceed to option 2 in these instances.

When I try option 2,  I get the error message as described in this post.   Below is the full console output when configured with option 2.  I have verified views exist for all required tables which are written to the console prior to the error occurring.  

Attached are my .config and EntityList.json files.  Anywhere *** appears the info has been redacted.  
[CDMUtil_ConsoleApp.dll.config.txt](https://github.com/microsoft/Dynamics-365-FastTrack-Implementation-Assets/files/9074116/CDMUtil_ConsoleApp.dll.config.txt)
[EntityList.json.txt](https://github.com/microsoft/Dynamics-365-FastTrack-Implementation-Assets/files/9074118/EntityList.json.txt)


****** Console Output With Attached Config/Json files ******************
12:28:47 info: CDMUtil.ConsoleApp[0] Key: TenantId Value: ***
12:28:47 info: CDMUtil.ConsoleApp[0] Key: AccessKey Value:***
12:28:47 info: CDMUtil.ConsoleApp[0] Key: ManifestURL Value: https://***.blob.core.windows.net/dynamics365-financeandoperations/ats-uat.sandbox.operations.dynamics.com/Tables/Tables.manifest.cdm.json
12:28:47 info: CDMUtil.ConsoleApp[0] Key: TargetDbConnectionString Value:***
12:28:47 info: CDMUtil.ConsoleApp[0] Key: AXDBConnectionString Value:***
12:28:47 info: CDMUtil.ConsoleApp[0] Key: ProcessEntities Value: true
12:28:47 info: CDMUtil.ConsoleApp[0] Key: DDLType Value: SynapseView
12:28:47 info: CDMUtil.ConsoleApp[0] Key: Schema Value: dbo
12:28:47 info: CDMUtil.ConsoleApp[0] Key: FileFormat Value: CSV
12:28:47 info: CDMUtil.ConsoleApp[0] Key: ParserVersion Value: 2.0
12:28:49 info: CDMUtil.ConsoleApp[0] Reading Manifest metadata https://***.dfs.core.windows.net/dynamics365-financeandoperations/ats-uat.sandbox.operations.dynamics.com/Tables/Tables.manifest.cdm.json
12:28:52 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/General
12:28:52 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/General/Main
12:28:53 info: CDMUtil.ConsoleApp[0] Manifest:Main.manifest.cdm.json
12:28:54 info: CDMUtil.ConsoleApp[0] Table:HcmEmployment
12:28:54 info: CDMUtil.ConsoleApp[0] Table:HcmWorker
12:28:54 info: CDMUtil.ConsoleApp[0] Table:HcmPositionDetail
12:28:54 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/General/Group
12:28:55 info: CDMUtil.ConsoleApp[0] Manifest:Group.manifest.cdm.json
12:28:55 info: CDMUtil.ConsoleApp[0] Table:HcmPersonDetails
12:28:55 info: CDMUtil.ConsoleApp[0] Table:HcmWorkerPrimaryPosition
12:28:55 info: CDMUtil.ConsoleApp[0] Table:HcmPositionWorkerAssignment
12:28:55 info: CDMUtil.ConsoleApp[0] Table:HcmTitle
12:28:56 info: CDMUtil.ConsoleApp[0] Table:HcmWorkerTitle
12:28:56 info: CDMUtil.ConsoleApp[0] Table:HcmPositionHierarchy
12:28:56 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/General/Parameter
12:28:56 info: CDMUtil.ConsoleApp[0] Manifest:Parameter.manifest.cdm.json
12:28:56 info: CDMUtil.ConsoleApp[0] Table:HcmPositionHierarchyType
12:28:56 info: CDMUtil.ConsoleApp[0] Manifest:General.manifest.cdm.json
12:28:56 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/System
12:28:56 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/System/SystemAdministration
12:28:57 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/System/SystemAdministration/Parameter
12:28:57 info: CDMUtil.ConsoleApp[0] Manifest:Parameter.manifest.cdm.json
12:28:57 info: CDMUtil.ConsoleApp[0] Table:SystemParameters
12:28:57 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/System/SystemAdministration/Reference
12:28:57 info: CDMUtil.ConsoleApp[0] Manifest:Reference.manifest.cdm.json
12:28:57 info: CDMUtil.ConsoleApp[0] Table:SRSAnalysisEnums
12:28:57 info: CDMUtil.ConsoleApp[0] Manifest:SystemAdministration.manifest.cdm.json
12:28:57 info: CDMUtil.ConsoleApp[0] Manifest:System.manifest.cdm.json
12:28:57 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/SupplyChain
12:28:58 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/SupplyChain/ProcurementAndSourcing
12:28:58 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/SupplyChain/ProcurementAndSourcing/WorksheetHeader
12:28:58 info: CDMUtil.ConsoleApp[0] Manifest:WorksheetHeader.manifest.cdm.json
12:28:58 info: CDMUtil.ConsoleApp[0] Table:PurchTable
12:28:58 info: CDMUtil.ConsoleApp[0] Manifest:ProcurementAndSourcing.manifest.cdm.json
12:28:58 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/SupplyChain/Inventory
12:28:59 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/SupplyChain/Inventory/Transaction
12:28:59 info: CDMUtil.ConsoleApp[0] Manifest:Transaction.manifest.cdm.json
12:28:59 info: CDMUtil.ConsoleApp[0] Table:WHSInventReserve
12:29:00 info: CDMUtil.ConsoleApp[0] Table:InventSum
12:29:00 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/SupplyChain/Inventory/Group
12:29:00 info: CDMUtil.ConsoleApp[0] Manifest:Group.manifest.cdm.json
12:29:00 info: CDMUtil.ConsoleApp[0] Table:WHSReservationHierarchyElement
12:29:00 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/SupplyChain/Inventory/Main
12:29:00 info: CDMUtil.ConsoleApp[0] Manifest:Main.manifest.cdm.json
12:29:00 info: CDMUtil.ConsoleApp[0] Table:PdsCatchWeightItem
12:29:00 info: CDMUtil.ConsoleApp[0] Table:WHSInventEnabled
12:29:01 info: CDMUtil.ConsoleApp[0] Table:WHSReservationHierarchyItem
12:29:01 info: CDMUtil.ConsoleApp[0] Table:InventDim
12:29:01 info: CDMUtil.ConsoleApp[0] Manifest:Inventory.manifest.cdm.json
12:29:01 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/SupplyChain/ProductInformationManagement
12:29:01 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/SupplyChain/ProductInformationManagement/Main
12:29:02 info: CDMUtil.ConsoleApp[0] Manifest:Main.manifest.cdm.json
12:29:02 info: CDMUtil.ConsoleApp[0] Table:EcoResProductTranslation
12:29:02 info: CDMUtil.ConsoleApp[0] Table:InventTable
12:29:02 info: CDMUtil.ConsoleApp[0] Manifest:ProductInformationManagement.manifest.cdm.json
12:29:02 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/SupplyChain/Transportation
12:29:03 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/SupplyChain/Transportation/WorksheetHeader
12:29:03 info: CDMUtil.Console
App[0] Manifest:WorksheetHeader.manifest.cdm.json
12:29:03 info: CDMUtil.ConsoleApp[0] Table:TMSPurchTable
12:29:03 info: CDMUtil.ConsoleApp[0] Manifest:Transportation.manifest.cdm.json
12:29:03 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/SupplyChain/Vendor
12:29:03 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/SupplyChain/Vendor/Main
12:29:03 info: CDMUtil.ConsoleApp[0] Manifest:Main.manifest.cdm.json
12:29:04 info: CDMUtil.ConsoleApp[0] Table:VendTable
12:29:04 info: CDMUtil.ConsoleApp[0] Manifest:Vendor.manifest.cdm.json
12:29:04 info: CDMUtil.ConsoleApp[0] Manifest:SupplyChain.manifest.cdm.json
12:29:04 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/Finance
12:29:04 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/Finance/Ledger
12:29:04 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/Finance/Ledger/Transaction
12:29:04 info: CDMUtil.ConsoleApp[0] Manifest:Transaction.manifest.cdm.json
12:29:04 info: CDMUtil.ConsoleApp[0] Table:SubledgerVoucherGeneralJournalEntry
12:29:04 info: CDMUtil.ConsoleApp[0] Table:ReasonTableRef
12:29:04 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/Finance/Ledger/Main
12:29:05 info: CDMUtil.ConsoleApp[0] Manifest:Main.manifest.cdm.json
12:29:05 info: CDMUtil.ConsoleApp[0] Table:MainAccountCategory
12:29:05 info: CDMUtil.ConsoleApp[0] Table:Ledger
12:29:05 info: CDMUtil.ConsoleApp[0] Table:LedgerChartOfAccounts
12:29:05 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/Finance/Ledger/TransactionLine
12:29:05 info: CDMUtil.ConsoleApp[0] Manifest:TransactionLine.manifest.cdm.json
12:29:06 info: CDMUtil.ConsoleApp[0] Table:GeneralJournalAccountEntry
12:29:06 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/Finance/Ledger/TransactionHeader
12:29:06 info: CDMUtil.ConsoleApp[0] Manifest:TransactionHeader.manifest.cdm.json
12:29:06 info: CDMUtil.ConsoleApp[0] Table:GeneralJournalEntry
12:29:06 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/Finance/Ledger/Reference
12:29:06 info: CDMUtil.ConsoleApp[0] Manifest:Reference.manifest.cdm.json
12:29:06 info: CDMUtil.ConsoleApp[0] Table:FiscalCalendarPeriod
12:29:06 info: CDMUtil.ConsoleApp[0] Manifest:Ledger.manifest.cdm.json
12:29:06 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/Finance/AccountsPayable
12:29:07 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/Finance/AccountsPayable/Group
12:29:07 info: CDMUtil.ConsoleApp[0] Manifest:Group.manifest.cdm.json
12:29:07 info: CDMUtil.ConsoleApp[0] Table:VendInvoiceDeclaration_IS
12:29:07 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/Finance/AccountsPayable/WorksheetHeader
12:29:07 info: CDMUtil.ConsoleApp[0] Manifest:WorksheetHeader.manifest.cdm.json
12:29:07 info: CDMUtil.ConsoleApp[0] Table:PurchTable_W
12:29:07 info: CDMUtil.ConsoleApp[0] Manifest:AccountsPayable.manifest.cdm.json
12:29:07 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/Finance/AccountingFoundation
12:29:07 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/Finance/AccountingFoundation/Group
12:29:08 info: CDMUtil.ConsoleApp[0] Manifest:Group.manifest.cdm.json
12:29:08 info: CDMUtil.ConsoleApp[0] Table:AccountingDistributionTemplate
12:29:08 info: CDMUtil.ConsoleApp[0] Manifest:AccountingFoundation.manifest.cdm.json
12:29:08 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/Finance/AccountsReceivable
12:29:08 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/Finance/AccountsReceivable/WorksheetHeader
12:29:08 info: CDMUtil.ConsoleApp[0] Manifest:WorksheetHeader.manifest.cdm.json
12:29:08 info: CDMUtil.ConsoleApp[0] Table:TransportationDocument
12:29:08 info: CDMUtil.ConsoleApp[0] Manifest:AccountsReceivable.manifest.cdm.json
12:29:08 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/Finance/FinancialDimensions
12:29:09 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/Finance/FinancialDimensions/Main
12:29:09 info: CDMUtil.ConsoleApp[0] Manifest:Main.manifest.cdm.json
12:29:09 info: CDMUtil.ConsoleApp[0] Table:DimensionAttributeValueSet
12:29:09 info: CDMUtil.ConsoleApp[0] Table:DimensionAttributeValue
12:29:09 info: CDMUtil.ConsoleApp[0] Table:DimensionAttributeValueCombination
12:29:10 info: CDMUtil.ConsoleApp[0] Table:DimensionFinancialTag
12:29:10 info: CDMUtil.ConsoleApp[0] Table:MainAccount
12:29:10 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/Finance/FinancialDimensions/Group
12:29:10 info: CDMUtil.ConsoleApp[0] Manifest:Group.manifest.cdm.json
12:29:10 info: CDMUtil.ConsoleApp[0] Table:DimensionHierarchy
12:29:10 info: CDMUtil.ConsoleApp[0] Table:DimensionHierarchyLevel
12:29:11 info: CDMUtil.ConsoleApp[0] Table:FinancialTagCategory
12:29:11 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/Finance/FinancialDimensions/Reference
12:29:11 info: CDMUtil.ConsoleApp[0] Manifest:Reference.manifest.cdm.json
12:29:11 info: CDMUtil.ConsoleApp[0] Table:DimensionAttributeValueGroupCombination
12:29:11 info: CDMUtil.ConsoleApp[0] Table:DimensionAttribute
12:29:12 info: CDMUtil.ConsoleApp[0] Table:DimensionAttributeLevelValue
12:29:12 info: CDMUtil.ConsoleApp[0] Table:DimensionAttributeDirCategory
12:29:12 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/Finance/FinancialDimensions/Miscellaneous
12:29:12 info: CDMUtil.ConsoleApp[0] Manifest:Miscellaneous.manifest.cdm.json
12:29:12 info: CDMUtil.ConsoleApp[0] Table:DimensionHierarchyIntegration
12:29:12 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/Finance/FinancialDimensions/Parameter
12:29:12 info: CDMUtil.ConsoleApp[0] Manifest:Parameter.manifest.cdm.json
12:29:12 info: CDMUtil.ConsoleApp[0] Table:DimensionParameters
12:29:12 info: CDMUtil.ConsoleApp[0] Manifest:FinancialDimensions.manifest.cdm.json
12:29:12 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/Finance/PublicSector
12:29:13 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/Finance/PublicSector/Miscellaneous
12:29:13 info: CDMUtil.ConsoleApp[0] Manifest:Miscellaneous.manifest.cdm.json
12:29:13 info: CDMUtil.ConsoleApp[0] Table:ConfirmingPO
12:29:13 info: CDMUtil.ConsoleApp[0] Manifest:PublicSector.manifest.cdm.json
12:29:13 info: CDMUtil.ConsoleApp[0] Manifest:Finance.manifest.cdm.json
12:29:13 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/Common
12:29:13 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/Common/GAB
12:29:13 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/Common/GAB/Main
12:29:14 info: CDMUtil.ConsoleApp[0] Manifest:Main.manifest.cdm.json
12:29:14 info: CDMUtil.ConsoleApp[0] Table:DirPersonName
12:29:14 info: CDMUtil.ConsoleApp[0] Table:LogisticsPostalAddress
12:29:14 info: CDMUtil.ConsoleApp[0] Table:DirPartyLocation
12:29:15 info: CDMUtil.ConsoleApp[0] Table:DirDunsNumber
12:29:15 info: CDMUtil.ConsoleApp[0] Table:LogisticsElectronicAddress
12:29:15 info: CDMUtil.ConsoleApp[0] Table:LogisticsLocation
12:29:16 info: CDMUtil.ConsoleApp[0] Table:DirPartyTable
12:29:16 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/Common/GAB/Group
12:29:16 info: CDMUtil.ConsoleApp[0] Manifest:Group.manifest.cdm.json
12:29:16 info: CDMUtil.ConsoleApp[0] Table:LogisticsAddressCountryRegion
12:29:16 info: CDMUtil.ConsoleApp[0] Manifest:GAB.manifest.cdm.json
12:29:16 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/Common/Customer
12:29:16 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/Common/Customer/Main
12:29:16 info: CDMUtil.ConsoleApp[0] Manifest:Main.manifest.cdm.json
12:29:17 info: CDMUtil.ConsoleApp[0] Table:CustTable
12:29:17 info: CDMUtil.ConsoleApp[0] Manifest:Customer.manifest.cdm.json
12:29:17 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/Common/Currency
12:29:17 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/Common/Currency/Group
12:29:17 info: CDMUtil.ConsoleApp[0] Manifest:Group.manifest.cdm.json
12:29:17 info: CDMUtil.ConsoleApp[0] Table:ExchangeRateType
12:29:18 info: CDMUtil.ConsoleApp[0] Table:Currency
12:29:18 info: CDMUtil.ConsoleApp[0] Table:ExchangeRateCurrencyPair
12:29:18 info: CDMUtil.ConsoleApp[0] Sub-Manifest:Tables/Common/Currency/Reference
12:29:18 info: CDMUtil.ConsoleApp[0] Manifest:Reference.manifest.cdm.json
12:29:18 info: CDMUtil.ConsoleApp[0] Table:ExchangeRate
12:29:18 info: CDMUtil.ConsoleApp[0] Manifest:Currency.manifest.cdm.json
12:29:18 info: CDMUtil.ConsoleApp[0] Manifest:Common.manifest.cdm.json
12:29:18 info: CDMUtil.ConsoleApp[0] Manifest:Tables.manifest.cdm.json
12:29:18 info: CDMUtil.ConsoleApp[0] Process Entities
12:29:18 info: CDMUtil.ConsoleApp[0] Entity:InventWarehouseOnHandV2Entity, Dependent tables: INVENTDIM,WHSINVENTRESERVE,WHSRESERVATIONHIERARCHYELEMENT,WHSRESERVATIONHIERARCHYITEM,ECORESPRODUCTTRANSLATION,INVENTTABLE,SYSTEMPARAMETERS,PDSCATCHWEIGHTITEM,WHSINVENTENABLED,INVENTDIM,INVENTSUM
Unhandled exception. System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CDMUtil.SQL.TSqlSyntaxHandler.ExplicitVisit(CreateViewStatement node) in C:\ReposExternal\Dynamics-365-FastTrack-Implementation-Assets\Analytics\CDMUtilSolution\CDMUtil\SQL\SQLHandler.cs:line 823
   at Microsoft.SqlServer.TransactSql.ScriptDom.CreateViewStatement.Accept(TSqlFragmentVisitor visitor)
   at Microsoft.SqlServer.TransactSql.ScriptDom.TSqlBatch.AcceptChildren(TSqlFragmentVisitor visitor)
   at Microsoft.SqlServer.TransactSql.ScriptDom.TSqlFragmentVisitor.ExplicitVisit(TSqlBatch node)
   at Microsoft.SqlServer.TransactSql.ScriptDom.TSqlBatch.Accept(TSqlFragmentVisitor visitor)
   at Microsoft.SqlServer.TransactSql.ScriptDom.TSqlScript.AcceptChildren(TSqlFragmentVisitor visitor)
   at Microsoft.SqlServer.TransactSql.ScriptDom.TSqlFragmentVisitor.ExplicitVisit(TSqlScript node)
   at Microsoft.SqlServer.TransactSql.ScriptDom.TSqlScript.Accept(TSqlFragmentVisitor visitor)
   at CDMUtil.SQL.TSqlSyntaxHandler..ctor(String _inputString, AppConfigurations c) in C:\ReposExternal\Dynamics-365-FastTrack-Implementation-Assets\Analytics\CDMUtilSolution\CDMUtil\SQL\SQLHandler.cs:line 790
   at CDMUtil.SQL.TSqlSyntaxHandler.updateViewSyntax(AppConfigurations c, List`1 metadataList) in C:\ReposExternal\Dynamics-365-FastTrack-Implementation-Assets\Analytics\CDMUtilSolution\CDMUtil\SQL\SQLHandler.cs:line 1011
   at CDMUtil.Manifest.ManifestReader.manifestToSQLMetadata(AppConfigurations c, List`1 metadataList, ILogger logger, String parentFolder) in C:\ReposExternal\Dynamics-365-FastTrack-Implementation-Assets\Analytics\CDMUtilSolution\CDMUtil\Manifest\ManifestHandler.cs:line 255
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at CDMUtil.ConsoleApp.Main(String[] args) in C:\ReposExternal\Dynamics-365-FastTrack-Implementation-Assets\Analytics\CDMUtilSolution\CDMUtil_ConsoleApp\Program.cs:line 36

C:\ReposExternal\Dynamics-365-FastTrack-Implementation-Assets\Analytics\CDMUtilSolution\CDMUtil_ConsoleApp\bin\Debug\net5.0\CDMUtil_ConsoleApp.exe (process 67332) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .

**Comment by TravisKale** [comment]
If I do that and also point to the entities manifest, the utility now creates the views I was after; however, it's still spitting out errors.  It's still throwing null reference exceptions on the same line in the SQLHandler class on line 823 of the ExplicitVisit method multiple times (3 to be exact).  Also a new error "Unable to cast object of type 'System.DBNull' to type 'System.String'.'" In method missingTables in the SQLHandler class line 386.  

Here is the full console output....
[ConsoleOutput.txt](https://github.com/microsoft/Dynamics-365-FastTrack-Implementation-Assets/files/9136151/ConsoleOutput.txt)

Side note possibly related:  When I first setup the export to data lake add-in, I added the entity "AadWorkerIntegrationEntity" as a test, it has a table "DirPerson" in the error state.  I don't need this entity, how do I remove it?  The add-in does not have functionality to remove an entity, only tables.  Do I need to manually edit the manifest?   Could this be causing any issues?, oddly enough the AadWorkerIntegrationEntity view is still created and queryable.
